# MySQL 설정
spring:
  datasource:
    # MySQL 설정
    driver-class-name : com.mysql.cj.jdbc.Driver
    # DB Source URL 설정
    url: jdbc:mysql://localhost:3306
    # DB 사용자 이름 설정
    username: root
    # DB 사용자이름에 대한 암호 설정
#    password: Abcd123@
  jpa:
    # true 설정 시, JPA 쿼리문 확인 가능
    # show-sql: true
    format_sql: true
    hibernate:
      # DDL(create, alter, drop) 정의 시, DB의 고유 기능을 사용할 수 있음.
      ddl-auto: create
      # JPA의 구현체인 Hibernate가 동작하면서, 발생한 SQL의 가독성을 높여줌.
      format_sql : true

logging.level:
  #  로그파일로 남기기 위함
  org.hibernate.SQL: debug
# 파라미터 보여줌
# org.hibernate.type: trace
